### ISSUE TITLE
Refactoring of Main.class in animation

### ISSUE THREAD

**Issue by aarexer** [qcha/tether#1]
Package: `com.github.qcha.animation`
Class: `Main`
Problems: 
1. All private methods in this class are duplicated each other. 
2. Method `start()` is very messy.
3. All label or button names should be constants of Main class.
4. All numbers(window size and etc) should be constants of Main.class.
5. Main window should not be resizable - we need to draw usual window with fixed size, size of buttons should be equals each other.

**Comment by RomanWayne** [comment]
sir, yes, sir

**Comment by aarexer** [comment]
Good job!
